name: RCB
description: "A Restaurant Chat-bot."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dialog_flowtter: ^0.3.3
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.17.3
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/ChatbotLogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/dialog_flow_auth.json
    - assets/icon/ChatbotLogolarge.png
    - assets/icon/ChatbotLogo.png
    - assets/icon/google.png
